name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GPR
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/smankusors/cloudera-docker/cloudera6.3:${GITHUB_SHA} .
    - name: Publish the Docker image to GPR
      run: docker push docker.pkg.github.com/smankusors/cloudera-docker/cloudera6.3:${GITHUB_SHA}
